const REAL_DATA = {
  "Friday 9/18": [
    {
      "day": "Friday 9/18",
      "time": "07:30AM – 09:10AM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Innovation Summit",
      "Title": "Innovation Summit Session I: Mapping, Imaging, and Ablation",
      "Authors": "Matthieu De Beule, Marco Götte, David N. Kenigsberg, Olurotimi Mesubi, Théophile Mohr Durdez, Jonathan Piccini, Vivek Y. Reddy, Ivo Roca-Luque, Kyungmoo Ryu, Devi G Nair, MD, FHRS, Prashanthan Sanders",
      "Affiliation": "FEops; University of Calgary | Stephenson Cardiac Imaging Centre, Libin Cardiovascular Institute; Florida Heart Rhythm Specialists and Fort Lauderdale Heart & Rhythm Surgical Center; Johns Hopkins University; Volta Medical; Duke University Hospital and the Duke Clinical Research Institute | Duke Heart Center; Mount Sinai Health System; Hospital Clínic de Barcelona; Abbott; St. Bernards Medical Center & Arrhythmia Research Group; University of Adelaide",
      "SpeakerTitles": "CEO & Co-Founder; Professor | Scientific Director; Clinical Cardiac Electrophysiologist & Founder; Assistant Professor of Medicine; CEO; Cardiac Electrophysiologist & Professor of Medicine and Population Health | Director of the Cardiac Electrophysiology section; Director of Cardiac Arrhythmia Services; Cardiac Electrophysiologist | Head of the Arrhythmia Section; Senior Director, R&D; Director of the Cardiac Electrophysiology & Research; Cardiac Electrophysiologist & Director of Cardiac Electrophysiology",
      "session_id": 1,
      "uid": "s_1",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "09:10AM – 12:00PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Innovation Summit",
      "Title": "Innovation Summit Session II: Beyond Conventional EP – PFA, Devices, Access, and Stroke Prevention",
      "Authors": "Andre d’Avila, Tina Baykaner, MD, MPH, Michael Curley, Matthew Hakimi, Gordon Ho, James Ip, Rohit Mehta, Steven Mickelsen, Jonathan Piccini, Ishu Rao, MD, Vivek Y. Reddy, Nicholas Serafini, Wilber Su, Rob Taft, Usha Tedrow, J. Peter Weiss, Jeffrey Winterfield, Ian Woollett, Devi G Nair, MD, FHRS, Prashanthan Sanders",
      "Affiliation": "Beth Israel Deaconess Medical Center; Department of Internal Medicine | Division of Cardiovascular Medicine and Electrophysiology | Stanford University; Thermedical; Cedars Sinai Medical Center; UC San Diego; Weill Cornell Medicine; Sanger Heart and Vascular Institute; Field Medical | Atraverse Medical, Inc. | Scripps Health; Duke University Hospital and the Duke Clinical Research Institute | Duke Heart Center; Impulse Dynamics; Mount Sinai Health System; Advocate Aurora Health Lutheran General Hospital; Banner-University Medical Center | University of Arizona College of Medicine; Nidus Biomedical; Brigham and Women’s Hospital | Harvard Medical School; Banner University of Arizona Medical Center Phoenix (BUMCP); Medical University of South Carolina; Sentara Norfolk General Hospital; St. Bernards Medical Center & Arrhythmia Research Group; University of Adelaide",
      "SpeakerTitles": "Director of Cardiac Arrhythmia Service; Assistant Professor; President; Cardiac Electrophysiologist; Associate Clinical Professor, Staff Cardiac Electrophysiologist; Professor; Cardiac Electrophysiologist; CEO | Board Member | Cardiac Electrophysiologist; Cardiac Electrophysiologist & Professor of Medicine and Population Health | Director of the Cardiac Electrophysiology section; Medical Director & Senior Vice President of Medical Affairs; Director of Cardiac Arrhythmia Services; Electrophysiologist | Director, Electrophysiology Laboratory; Director of Cardiac Electrophysiology | Professor of Medicine; Vice President, R&D; Director, Clinical Cardiac Electrophysiology Program | Associate Professor of Medicine; Cardiac Electrophysiologist; Hank and Laurel Greer Chair in Clinical Cardiac Electrophysiology | Professor of Medicine; Cardiac Electrophysiologist | Director of the Electrophysiology Laboratory; Director of the Cardiac Electrophysiology & Research; Cardiac Electrophysiologist & Director of Cardiac Electrophysiology",
      "session_id": 2,
      "uid": "s_2",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "01:00PM – 01:10PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "General",
      "Title": "Opening Remarks",
      "Authors": "Jonathan Piccini, Prashanthan Sanders",
      "Affiliation": "Duke University Hospital and the Duke Clinical Research Institute | Duke Heart Center; University of Adelaide",
      "SpeakerTitles": "Cardiac Electrophysiologist & Professor of Medicine and Population Health | Director of the Cardiac Electrophysiology section; Cardiac Electrophysiologist & Director of Cardiac Electrophysiology",
      "session_id": 3,
      "uid": "s_3",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "01:10PM – 01:55PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Featured Keynote",
      "Title": "Computable Cardiology: How AI is Transforming the Future of Cardiovascular Medicine",
      "Authors": "Murali Aravamudan, Jonathan Piccini",
      "Affiliation": "nference; Duke University Hospital and the Duke Clinical Research Institute | Duke Heart Center",
      "SpeakerTitles": "Co-Founder & Chief Executive Officer; Cardiac Electrophysiologist & Professor of Medicine and Population Health | Director of the Cardiac Electrophysiology section",
      "session_id": 4,
      "uid": "s_4",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "02:00PM – 02:45PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Session",
      "Title": "Is AF Mapping Ready for Routine Clinical Procedure?",
      "Authors": "Isabel Deisenhofer, MD, Vadim V. Fedorov, Prapa Kanagaratnam, Saar Moisa, Shlomo Shpun, Sanjiv Narayan",
      "Affiliation": "German Heart Center Munich Department of Electrophysiology; The Ohio State University Wexner Medical Center; Imperial College Healthcare, St Mary’s Hospital, Cardiology; Kardium; TechWald Holding S.p.A.; Stanford University",
      "SpeakerTitles": "Head, Department of Electrophysiology; Corrine Frick Research Chair in Heart Failure and Arrhythmia; Consultant Cardiologist; Senior Director of Product Management; Chief Scientific Office; Professor of Medicine | Director of the NIH T32 Computational Medicine Training Program (CHIP) | Co-Director of the Arrhythmia Center",
      "session_id": 5,
      "uid": "s_5",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "02:00PM – 02:45PM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Making AFib Care Pathways Work: From Evidence to Execution Across Real-World Settings – Powered by Johnson & Johnson MedTech",
      "Authors": "T. Jared Bunch, Edward Gerstenfeld, Andrea Robinson, Emma Svennberg, MD, PhD, Daniel Valcicak, Jamie Treskot",
      "Affiliation": "Division of Cardiovascular Medicine at University of Utah Hospital; University of California, San Francisco; Riverside Methodist Hospital, OhioHealth; Karolinska University Hospital; VHC Health; Johnson & Johnson MedTech",
      "SpeakerTitles": "Associate Chief of Cardiology; Professor of Medicine; Nurse Practitioner; Assistant professor | Electrophysiologist; Cardiac Electrophysiology PA; Regional Therapy Advancement Manager",
      "session_id": 6,
      "uid": "s_6",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "02:00PM – 02:45PM",
      "room": "Main Stage 2",
      "type": "session",
      "Track": "Session",
      "Title": "AI in Arrhythmia Care: Opportunities, Pitfalls, and Practical Applications for Allied Professionals",
      "Authors": "Alicia C. Rodriguez, Sean Shoffstall, Yekaterina Spivak, Erica Zado, PAC, FHRS, Adrian Elliott",
      "Affiliation": "Bloomer Tech; PaceMate; Children’s Hospital of Philadelphia | Welcome Baby 247; Hospital of the University of Pennsylvania; Adelaide University, Royal Adelaide Hospital",
      "SpeakerTitles": "Founder & CEO; Chief Product Officer; Pediatric Electrophysiology Physician Assistant | IBCLC & Co-founder; Physician Assistant; Senior Research Fellow | Associate Professor",
      "session_id": 7,
      "uid": "s_7",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "02:00PM – 02:45PM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Consumer Design in Rhythm Monitoring: Unlocking Opportunities in Agentic AI, Treatment Optimization and Research – Powered by Wearlinq",
      "Authors": "Zachi Itzhak Attia, MSEE, PhD, Rex Gale, Suneet Mittal, Konrad Morzkowski, Jeanne Poole, Samuel F. Sears, Albert Rogers",
      "Affiliation": "Mayo Clinic; TEDxAjijic; Valley Health System; Wearlinq; University of Washington Medical Center and School of Medicine; East Carolina Heart Institute; Stanford University",
      "SpeakerTitles": "Director of AI; Founder | Patient Advocate; Chair, Cardiovascular Service Line; Co-Founder & CEO; Cardiac Electrophysiologist | Director | Professor of Cardiology and Medicine; Professor in the Departments of Psychology and Cardiovascular Sciences | Division Chief of Innovation and Research | Associate Director of the ECU Cardiology Fellowship; Cardiac Electrophysiologist",
      "session_id": 8,
      "uid": "s_8",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "02:00PM – 02:45PM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Drowning in Alerts: How AI Is Redefining What Deserves Clinical Attention in Remote Monitoring – Powered by Implicity",
      "Authors": "Tina Baykaner, MD, MPH, David Duncker, MD, FHRS, Rakesh Gopinathannair, Joshua Lampert, Arnaud Rosier, Elaine Wan, Manish Wadhwa",
      "Affiliation": "Department of Internal Medicine | Division of Cardiovascular Medicine and Electrophysiology | Stanford University; Hannover Medical School; Kansas City Heart Rhythm Institute; Mount Sinai Heart in The Mount Sinai Hospital; Implicity; Columbia University Medical Center, College of Physicians and Surgeons | New York-Presbyterian Hospital; SummaCor | San Diego Arrhythmia Associates | Implicity",
      "SpeakerTitles": "Assistant Professor; Head of Hannover Heart Rhythm Center; Director of Cardiac Electrophysiology Laboratories; Cardiac Electrophysiologist & Medical Director of Machine Learning; Chief Executive Officer & Founder; Esther Aboodi Associate Professor of Medicine in Cardiology and Cardiac Electrophysiology | Attending Physician at New York-Presbyterian Hospital; Chief Executive Officer | Cardiac Electrophysiologist | Medical Advisor",
      "session_id": 9,
      "uid": "s_9",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "02:50PM – 03:35PM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Beyond Alerts: Building the Continuous Cardiovascular Care Platform – Powered by 91Life",
      "Authors": "Kelly Arps, Bleron Baraliu, Thomas Deering, Gerhard Hindricks, MD, PhD, Jessica Mullenix, George Stuart Mendenhall",
      "Affiliation": "University of Michigan; 91Life; Piedmont Heart Institute; Charite University Hospital, Berlin; U.S. Department of Veterans Affairs Cardiology Office; Scripps Memorial Hospital | Everbeat",
      "SpeakerTitles": "Cardiac Electrophysiologist; CEO; Chief, Cardiovascular Centers of Excellence | Chief, Arrhythmia Center; Medical Director; Cardiac Electrophysiology Nurse Practitioner; Cardiac Electrophysiologist and Researcher | Chief Medical Officer",
      "session_id": 10,
      "uid": "s_10",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "02:50PM – 03:35PM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Why Startups Get Stuck Before First-in-Human and How to Fix It – Powered by 3PH Alliance/HRCRS",
      "Authors": "Leanne Bakke, Srijoy Mahapatra, Jose Osorio, Christopher Porterfield, Luke Ralston, Jason Quill, J. Peter Weiss",
      "Affiliation": "BioSim Innovations; Abbott; HCA Florida Miami | 3PH Alliance | Heart Rhythm Clinical Research Solutions; Aurora Denver Cardiology Associates; US Food & Drug Administration; Structural Heart Venture; Banner University of Arizona Medical Center Phoenix (BUMCP)",
      "SpeakerTitles": "Co-Founder & CEO; World Wide General Manager, Left Atrial Appendage Management; Medical Director of Electrophysiology – HCA Florida Miami |  Founder and CMO | Founder and President; Cardiac Electrophysiologist; Biomedical Engineer; Founder; Cardiac Electrophysiologist",
      "session_id": 11,
      "uid": "s_11",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "03:00PM – 04:20PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Pitch Competition",
      "Title": "Pitch Competition I",
      "Authors": "Sajol Ghoshal, Anna Li, Tony Ma, Sean McCormick, Naoki Tomii",
      "Affiliation": "Advanced TeleSensors Inc.; Korion Health; Benten Technologies, Inc.; Atrility Medical; The University of Tokyo",
      "SpeakerTitles": "Chief Executive Officer; CEO; CEO | Co-founder; CEO; Associate Professor",
      "session_id": 12,
      "uid": "s_12",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "03:30PM – 03:50PM",
      "room": "HRStv Studio",
      "type": "session",
      "Track": "General",
      "Title": "One Patient, Two Timelines: Rethinking Long-Term Continuous Cardiac Monitoring – Live from HRStv",
      "Authors": "Chris Irving, Mintu Turakhia, Nino Isakadze",
      "Affiliation": "Murj Inc.; iRhythm Technologies, Inc. | Stanford University; Johns Hopkins Hospital",
      "SpeakerTitles": "Co-Founder, Chief Experience Officer & Head of Design; Chief Medical and Scientific Officer + EVP, Product Management and Innovation | Professor of Medicine and Cardiac Electrophysiologist; Assistant Professor of Medicine | Cardiac Electrophysiologist",
      "session_id": 13,
      "uid": "s_13",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "03:40PM – 04:00PM",
      "room": "Hyde Park",
      "type": "session",
      "Track": "Hot Takes Exchange",
      "Title": "ASCs Will Improve EP Care Delivery and Access",
      "Authors": "Dhanunjaya R. Lakkireddy, Usman Siddiqui, Rohit Mehta",
      "Affiliation": "HCA Midwest in Overland Park, Kansas; Advent Health Celebration; Sanger Heart and Vascular Institute",
      "SpeakerTitles": "Executive Medical Director of the Kansas City Heart Rhythm Institute; Electrophysiologist; Cardiac Electrophysiologist",
      "session_id": 14,
      "uid": "s_14",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "03:55PM – 04:40PM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Innovating How We Do Research: The HRS Research Network",
      "Authors": "Patrick Boyle, Thomas Deneke, Luigi Di Biase, MD, PhD, FHRS, Larry Jackson, II, Valentina Kutyifa, Douglas Packer, Pugazhendhi Vijayaraman, Kenneth Bilchick",
      "Affiliation": "University of Washington; Clinic for Arrhythmology, University Heart Center Nuremberg, Paracelsus Medical University; Albert Einstein College of Medicine at Montefiore Health System; Duke University Medical Center; University of Rochester Medical Center; Intermountain Medical Center; Geisinger Heart & Vascular Institute; University of Virginia",
      "SpeakerTitles": "Associate Professor of Bioengineering; Cardiac Electrophysiologist; Clinical Cardiac Electrophysiology; Associate Professor of Medicine; Professor of Medicine; Professor of Medicine; Director, CCEP Fellowship; Associate Professor of Medicine | Clinical Cardiologist & Electrophysiologist",
      "session_id": 15,
      "uid": "s_15",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "03:55PM – 04:40PM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Drug Development for Arrhythmias: From Symptom Relief to Digital-Era Outcomes – Powered by Milestone Pharmaceuticals",
      "Authors": "Brynn Dechert-Crooks, James Ip, Oliver Monfredi, Andrea Russo, MD, Kamala Tamirisa, Gregory Marcus",
      "Affiliation": "University of Michigan Congenital Heart Center; Weill Cornell Medicine; University of Virginia; Cooper University Hospital; UT Southwestern Medical Center; Univ of California, San Francisco | JAMA",
      "SpeakerTitles": "Pediatric Electrophysiology Nurse Practitioner; Professor; Associate Professor of Medicine, Medical Director of the Complex Lead Management and Extraction Center of Excellence; Academic Chief, Division of Cardiology | Director, Cardiac Electrophysiology and Arrhythmia Services | Director, CCEP Fellowship; Clinical Cardiac Electrophysiologist | Associate Professor of Internal Medicine in the Division of Cardiology | Director of Electrophysiology Research; Cardiac Electrophysiologist & Professor of Medicine | Associate Chief of Cardiology for Research",
      "session_id": 16,
      "uid": "s_16",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "04:30PM – 04:50PM",
      "room": "Hyde Park",
      "type": "session",
      "Track": "Hot Takes Exchange",
      "Title": "The 12-lead ECG Has Been Around For a While, Can’t We Find Something Better?",
      "Authors": "Zak Loring, Gaurav Upadhyay, Mehak Dhande",
      "Affiliation": "Duke University Medical Center; The University of Chicago Medicine; Stanford University, Stanford Healthcare",
      "SpeakerTitles": "Cardiac Electrophysiologist; Professor of Medicine; Interventional Cardiac Electrophysiologist | Physician Scientist",
      "session_id": 17,
      "uid": "s_17",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "04:45PM – 05:30PM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "New Autonomic Approaches to Complement Arrhythmia Care – Powered by SymKardia",
      "Authors": "Kelly Arps, Malcolm Finlay, Marat Fudim, Jonathan Piccini, Vivek Y. Reddy, Kalyanam Shivkumar, Prashanthan Sanders",
      "Affiliation": "University of Michigan; Barts Heart Centre | Echopoint Medical Ltd | Rhythm AI Ltd; Duke University Medical Center; Duke University Hospital and the Duke Clinical Research Institute | Duke Heart Center; Mount Sinai Health System; UCLA Health System, UCLA Cardiac Arrhythmia Center & EP Programs; University of Adelaide",
      "SpeakerTitles": "Cardiac Electrophysiologist; Consultant Cardiologist | Chief Medical Officer | Founder; Associate Professor & Heart Failure Cardiologist; Cardiac Electrophysiologist & Professor of Medicine and Population Health | Director of the Cardiac Electrophysiology section; Director of Cardiac Arrhythmia Services; Professor & Director, Center for Interventional Programs; Cardiac Electrophysiologist & Director of Cardiac Electrophysiology",
      "session_id": 18,
      "uid": "s_18",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "04:45PM – 05:30PM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "The Next Generation of Ambulatory ECG Monitoring and Virtual Arrhythmia Detection – Powered by HelpWear",
      "Authors": "Ilyas Colombowala, Derek Exner, Martha G. Ferrara, Rod Passman, Hee Tae Yu,AMbarish Pandey",
      "Affiliation": "Octagos; HelpWear Inc. | Cumming School of Medicine at University of Calgary; White Plains Hospital-Montefiore Health Systems; Northwestern University Feinberg School of Medicine; Yonsei University College of Medicine; University of Texas Southwestern Medical Center",
      "SpeakerTitles": "Chief Medical and Compliance Officer; Chief Medical Officer | Professor; Family Nurse Practitioner | Assistant Director EP Services; Jules Reingold Professor of Electrophysiology & Cardiac Electrophysiologist; Cardiac Electrophysiologist, Associate Professor of Medicine; Associate Professor of Cardiology in Internal Medicine",
      "session_id": 19,
      "uid": "s_19",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "04:45PM – 05:30PM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "From Hype to Impact: How AI Can Standardize EP Workflows—and Help Treat the Complex AF Patient – Powered by Volta Medical",
      "Authors": "Tina Baykaner, MD, MPH, Kristie Coleman, Isabel Deisenhofer, MD, Christopher Liu, Théophile Mohr Durdez, Paul Zei",
      "Affiliation": "Department of Internal Medicine | Division of Cardiovascular Medicine and Electrophysiology | Stanford University; Lenox Hill Hospital; German Heart Center Munich Department of Electrophysiology; Weill Cornell Medicine System | New York-Presbyterian Hospital; Volta Medical; Brigham and Women’s Hospital",
      "SpeakerTitles": "Assistant Professor; Director, Cardiac Electrophysiology Research; Head, Department of Electrophysiology; Director of EP Services; CEO; Cardiac Electrophysiologist",
      "session_id": 20,
      "uid": "s_20",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "04:45PM – 05:30PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Session",
      "Title": "Can Gene Therapy Deliver the Promise of Personalized EP Therapy?",
      "Authors": "Vassilios Bezzerides, Brynn Dechert-Crooks, Nathan Miller, Jason Roberts, Jonathan Schwartz, Robert Whitehill, Dominic Abrams",
      "Affiliation": "Boston Children’s Hospital; University of Michigan Congenital Heart Center; St. Louis Children’s Hospital; McMaster University; Rocket Pharmaceuticals; Childrens Healthcare of Atlanta Cardiology",
      "SpeakerTitles": "Assistant Professor of Pediatrics; Pediatric Electrophysiology Nurse Practitioner; Electrophysiology Nurse; Cardiac Electrophysiologist; Chief Scientific and Gene Therapy Officer; Pediatric Cardiac Electrophysiologist; Co-Director of the Center for Cardiovascular Genetics",
      "session_id": 21,
      "uid": "s_21",
      "isMedtronic": false
    },
    {
      "day": "Friday 9/18",
      "time": "04:45PM – 05:30PM",
      "room": "Main Stage 2",
      "type": "session",
      "Track": "Session",
      "Title": "Permanent Pacing but not for Bradycardia",
      "Authors": "Daniel J. Friedman, Karl-Heinz Kuck, Margaret Infeld, Daniel L. Lustgarten, Andrea Russo, MD, Robert Kowal",
      "Affiliation": "Duke University School of Medicine; University Hospital Luebeck; Tufts Medical Center; The University of Vermont College of Medicine; Cooper University Hospital; Medtronic",
      "SpeakerTitles": "Cardiac Electrophysiologist | Associate Professor; Consultant Cardiologist; Cardiac Electrophysiologist | Assistant Professor; Professor of Medicine; Academic Chief, Division of Cardiology | Director, Cardiac Electrophysiology and Arrhythmia Services | Director, CCEP Fellowship; Vice President and General Manager, Cardiac Pacing Therapies | Cardiac Electrophysiologist",
      "session_id": 22,
      "uid": "s_22",
      "isMedtronic": true
    },
    {
      "day": "Friday 9/18",
      "time": "05:45PM – 06:45PM",
      "room": "Abstract Happy Hour – Main Stage 1, Main Stage 2, Roundtable 1, Roundtable 2, Roundtable 3, ConneXions Lounge",
      "type": "session",
      "Track": "Abstract Happy Hour",
      "Title": "HRX Abstract Happy Hour I – Powered by 91Life",
      "Authors": "Michel Abou Khalil, Moez Alnazeer, Simrat Arora, Ulrika Birgersdotter-Green, Jian Cao, Brandon Doty, Alex El Darzi, Carlo El Khoury, Hassan Elshirbiny, Muhammad Fazal, Masato Hachisuka, Sylvia Hanna, Gene Hu, Sei Iwai,AMy Kleinhans, Yingshuo Liu, Abhishek Maan, Andrew Nguyen, Jonathan Piccini, Cara Schaaf,AMber Seiler, Hiroshi Seno, Nicholas Sommers, Ana Sopa, Anand Thiyagarajah, Venkatakrishna Tholakanahalli, Nestor Vasquez, Jeffrey Winterfield, Neal Bhatia, Yaariv Khaykin, Bradley Knight, Anne Kroman, Nishaki Mehta, Kamala Tamirisa",
      "Affiliation": "Tulane Research Innovation for Arrhythmia Discovery (TRIAD); Baylor College of Medicine; University of Colorado; UC San Diego Health System; Medtronic Inc.; University of Nebraska Medical Center; TRIAD-Tulane University; Tulane University – TRIAD; HDZ-NRW Bad Oeynhausen, Germany; Stanford University; Nippon Medical School; Vector Remote Care; UTSW; WMC Health Network; HonorHealth; Tulane University School of Medicine; The University of Toledo; Keck Medicine of USC; Duke University Hospital and the Duke Clinical Research Institute | Duke Heart Center; Upstate Cardiology; CV Remote Solutions | LeBauer Cardiology; Institute of Science Tokyo; Medical College of Wisconsin; 91Life; University of Adelaide; University of Minnesota | Minneapolis VA Health Care System; Johns Hopkins Hospital; Medical University of South Carolina; Emory University Hospital System; Myant Health; Northwestern Medicine | Bluhm Cardiovascular Institute (BCVI); William Beaumont Oakland University School of Medicine; UT Southwestern Medical Center",
      "SpeakerTitles": "Medical Intern & Research Fellow; Cardiology Fellow; Internal Medicine Resident; Cardiac Electrophysiologist | Professor of Medicine; Research Program Director and Technical Fellow; Internal Medicine Resident; Cardiology Post-Doc; Research Scientist; Electrophysiology & Rhythmology fellow; Cardiology Fellow; Assistant Professor; Lead Solutions Engineer; Section Chief, Cardiac Electrophysiology; Electrophysiology Nurse Practitioner; Biostatistician; Cardiac Electrophysiologist; Medical Student; Cardiac Electrophysiologist & Professor of Medicine and Population Health | Director of the Cardiac Electrophysiology section; RN; Chief Operating Officer | EP Nurse Practitioner & Arrhythmia Program Services Coordinator; Assistant Professor; Cardiology Fellow; Machine Learning Engineer; Electrophysiology Fellow; Professor of Medicine | Chief-Cardiac Electrophysiology; Cardiac Electrophysiologist; Hank and Laurel Greer Chair in Clinical Cardiac Electrophysiology | Professor of Medicine; Cardiac Electrophysiologist | Co-Director of the Complex Ventricular Tachycardia Ablation Program; Chief Medical Information Officer; Director of Cardiac Electrophysiology | Director of the Heart Rhythm Center; Associate Professor of Cardiac Electrophysiology | Director of the Lead Management Program, the Cardiac Device Clinic, and MUSC Heart Station; Associate Professor of Medicine; Clinical Cardiac Electrophysiologist | Associate Professor of Internal Medicine in the Division of Cardiology | Director of Electrophysiology Research",
      "session_id": 23,
      "uid": "s_23",
      "isMedtronic": true
    }
  ],
  "Saturday 9/19": [
    {
      "day": "Saturday 9/19",
      "time": "07:50AM – 08:00AM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "General",
      "Title": "Saturday Opening Remarks",
      "Authors": "Jonathan Piccini, Prashanthan Sanders",
      "Affiliation": "Duke University Hospital and the Duke Clinical Research Institute | Duke Heart Center; University of Adelaide",
      "SpeakerTitles": "Cardiac Electrophysiologist & Professor of Medicine and Population Health | Director of the Cardiac Electrophysiology section; Cardiac Electrophysiologist & Director of Cardiac Electrophysiology",
      "session_id": 24,
      "uid": "s_24",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "08:00AM – 08:45AM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Featured Keynote",
      "Title": "Scaling Innovation: Leadership, Strategy, and the Future of Cardiac Arrhythmia Care",
      "Authors": "Rebecca Seidel, Suneet Mittal",
      "Affiliation": "Medtronic; Valley Health System",
      "SpeakerTitles": "SVP and President, Electrophysiology Therapies; Chair, Cardiovascular Service Line",
      "session_id": 25,
      "uid": "s_25",
      "isMedtronic": true
    },
    {
      "day": "Saturday 9/19",
      "time": "08:50AM – 09:35AM",
      "room": "Main Stage 2",
      "type": "session",
      "Track": "Session",
      "Title": "Social Robotica and Future of Patient Education as Part of Innovative Care Models",
      "Authors": "Sirena Bridges, Trudie Lobban, Emma Svennberg, MD, PhD, Ajay Tripuraneni, Mellanie True Hills, Kathryn Wood, Alessandra Pina",
      "Affiliation": "VA Tennessee Valley HealthCare System; Arrhythmia Alliance | AF Association | STARS; Karolinska University Hospital; Baylor Scott & White Health;AMerican Foundation for Women’s Health & StopAfib.org; Emory University School of Nursing; Adelaide University and Royal Adelaide Hospital",
      "SpeakerTitles": "Cardiac Device Nurse Practitioner; Founder & CEO; Assistant professor | Electrophysiologist; Cardiac Electrophysiologist; Founder & CEO; Associate Professor; Electrophysiology Fellow and PhD Student",
      "session_id": 26,
      "uid": "s_26",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "08:50AM – 09:35AM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "From First-in-Human to Real Use: Why MedTech Innovations Stall – Powered by 3PH Alliance/HRCRS",
      "Authors": "Jackson Hair, David Krummen, Michael Lesh, Jason Moore, Joe Sasson, Rebecca Seidel, Paul Wang, Babak Nazer",
      "Affiliation": "U.S. Food and Drug Administration; University of California San Diego; UCSF | Quench, Inc.; 3PH Alliance/HRCRS; MedAxiom – An ACC Company; Medtronic; Stanford Medicine; University of Washington",
      "SpeakerTitles": "Biomedical Engineer; Professor of Clinical Medicine; Adjunct Professor of Medicine | Founder & CEO; Chief Commercial Officer; Chief Commercial Officer and EVP, MedAxiom Venture; SVP and President, Electrophysiology Therapies; Director of the Stanford Cardiac Arrhythmia Service & Professor of Medicine and of Bioengineering; Professor of Medicine and Bioengineering | Cardiac Electrophysiologist",
      "session_id": 27,
      "uid": "s_27",
      "isMedtronic": true
    },
    {
      "day": "Saturday 9/19",
      "time": "08:50AM – 09:35AM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "AI Is Ready. Are We? Rethinking Cardiac Monitoring, Automation, and Research in the Intelligence Era – Powered by PaceMate",
      "Authors": "Eugene Fu, Anne Kroman, Gregory Marcus, Lisa Roelle, Sean Shoffstall, Benjamin Steinberg, Camille Frazier-Mills",
      "Affiliation": "OhioHealth Heart & Vascular Physicians; Medical University of South Carolina; Univ of California, San Francisco | JAMA; Washington University in St. Louis & St. Louis Children’s Hospital; PaceMate; Denver Health Medical Center; Duke University Health System",
      "SpeakerTitles": "Clinical Cardiac Electrophysiologist; Associate Professor of Cardiac Electrophysiology | Director of the Lead Management Program, the Cardiac Device Clinic, and MUSC Heart Station; Cardiac Electrophysiologist & Professor of Medicine | Associate Chief of Cardiology for Research; Pediatric Electrophysiology Physician Assistant; Chief Product Officer; Director of Cardiac Electrophysiology; Cardiac Electrophysiologist | Professor of Medicine",
      "session_id": 28,
      "uid": "s_28",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "08:50AM – 09:35AM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Advances in Optimizing Conduction System Pacing – Powered by AliveCor",
      "Authors": "Neal Bhatia, Mikhael El-Chami, Daniel Frisch, Nino Isakadze, Ajay Pillai, Alan Sugrue, Pugazhendhi Vijayaraman, Eugene Chung",
      "Affiliation": "Emory University Hospital System; Emory University; Thomas Jefferson University Hospital; Johns Hopkins Hospital; VCU Health; Mayo Clinic Rochester; Geisinger Heart & Vascular Institute; Massachusetts General Hospital/Harvard Medical School",
      "SpeakerTitles": "Cardiac Electrophysiologist | Co-Director of the Complex Ventricular Tachycardia Ablation Program; Electrophysiologist | Professor of Medicine; Section Chief of Electrophysiology | Professor; Assistant Professor of Medicine | Cardiac Electrophysiologist; Assistant Professor of Medicine; Cardiac Electrophysiologist; Director, CCEP Fellowship; Director, Sports Electrophysiology Clinic",
      "session_id": 29,
      "uid": "s_29",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "08:50AM – 09:35AM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Session",
      "Title": "Seeing the Future with ICE",
      "Authors": "Christoph Hennersperger, Josef Kautzner, Bradley Knight, Dhanunjaya R. Lakkireddy, Paul Zei, Tina Baykaner, MD, MPH",
      "Affiliation": "LUMA Vision; IKEM Prague; Northwestern Medicine | Bluhm Cardiovascular Institute (BCVI); HCA Midwest in Overland Park, Kansas; Brigham and Women’s Hospital; Department of Internal Medicine | Division of Cardiovascular Medicine and Electrophysiology | Stanford University",
      "SpeakerTitles": "Co-Founder & Chief Technology Officer; Cardiac Electrophysiologist | Director of the Heart Centre and Head of Department of Cardiology; Director of Cardiac Electrophysiology | Director of the Heart Rhythm Center; Executive Medical Director of the Kansas City Heart Rhythm Institute; Cardiac Electrophysiologist; Assistant Professor",
      "session_id": 30,
      "uid": "s_30",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "09:40AM – 10:25AM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Accelerating AVIM Therapy for Hypertensive Heart Disease: The Medtronic / Orchestra BioMed Innovation Partnership – Powered by Orchestra Biomed",
      "Authors": "David Hochman, Robert Kowal, Charles Love, Andrea Russo, MD, Vivek Y. Reddy",
      "Affiliation": "Orchestra BioMed; Medtronic; Johns Hopkins Hospital; Cooper University Hospital; Mount Sinai Health System",
      "SpeakerTitles": "Chairman & CEO; Vice President and General Manager, Cardiac Pacing Therapies | Cardiac Electrophysiologist; Professor of Medicine; Academic Chief, Division of Cardiology | Director, Cardiac Electrophysiology and Arrhythmia Services | Director, CCEP Fellowship; Director of Cardiac Arrhythmia Services",
      "session_id": 31,
      "uid": "s_31",
      "isMedtronic": true
    },
    {
      "day": "Saturday 9/19",
      "time": "09:40AM – 10:25AM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "From Promise to Practice: Implementing the Power of ECG-AI in Everyday Care – Powered by Anumana",
      "Authors": "Samir Awasthi, Chad Bonhomme, Camille Frazier-Mills, Eleanor Huff,AMbarish Pandey, Rahul Doshi",
      "Affiliation": "Anumana, Inc.; Westfield Physician Holdings, LLC; Duke University Health System; Baylor Scott & White The Heart Hospital; University of Texas Southwestern Medical Center; ASU School of Medicine and Medical Engineering",
      "SpeakerTitles": "Vice President, Clinical Research; President & Electrophysiologist; Cardiac Electrophysiologist | Professor of Medicine; Vice President, CV Service Line Operations; Associate Professor of Cardiology in Internal Medicine; Chief Cardiovascular Medicine",
      "session_id": 32,
      "uid": "s_32",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "09:40AM – 10:25AM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Session",
      "Title": "Reimbursement for AI Tools in Arrhythmia Care",
      "Authors": "Zachi Itzhak Attia, MSEE, PhD, Matthew Kalscheur, Suraya Hani Kamsani, Kalyanam Shivkumar, Ajay Tripuraneni, Christopher Liu",
      "Affiliation": "Mayo Clinic; University of Wisconsin School of Medicine and Public Health; National Heart Institute, Malaysia; UCLA Health System, UCLA Cardiac Arrhythmia Center & EP Programs; Baylor Scott & White Health; Weill Cornell Medicine System | New York-Presbyterian Hospital",
      "SpeakerTitles": "Director of AI; Cardiac Electrophysiologist & Clinical Informaticist; Consultant Cardiologist and Electrophysiologist; Professor & Director, Center for Interventional Programs; Cardiac Electrophysiologist; Director of EP Services",
      "session_id": 33,
      "uid": "s_33",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "09:40AM – 10:25AM",
      "room": "Main Stage 2",
      "type": "session",
      "Track": "Session",
      "Title": "LAA Occlusion Devices: Iterating, Innovating, and Improving",
      "Authors": "Christopher Ellis, James Freeman, Bradley Knight, Venkatakrishna Tholakanahalli, Michael Lesh",
      "Affiliation": "Vanderbilt University Medical Center; Yale University School of Medicine; Northwestern Medicine | Bluhm Cardiovascular Institute (BCVI); University of Minnesota | Minneapolis VA Health Care System; UCSF | Quench, Inc.",
      "SpeakerTitles": "Director LAA (Left Atrial Appendage) Program | Director AF Center; Professor of Medicine; Director of Cardiac Electrophysiology | Director of the Heart Rhythm Center; Professor of Medicine | Chief-Cardiac Electrophysiology; Adjunct Professor of Medicine | Founder & CEO",
      "session_id": 34,
      "uid": "s_34",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "09:40AM – 10:25AM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "The Time Behind the Tasks: APPs and the 32 Steps of Remote Monitoring – Powered by Vector Remote",
      "Authors": "Aileen Ferrick, Kevin Hoffman,AMy Kleinhans, David Lin, Jessica Mullenix,AMy Tucker, Krishna Pundi",
      "Affiliation": "White Plains Hospital; Vector Remote Care; HonorHealth; Cardiovascular Division at Hospital of the University of Pennsylvania; U.S. Department of Veterans Affairs Cardiology Office; Sanger Heart & Vascular Institute (SHVI); Palo Alto VA Hospital",
      "SpeakerTitles": "Assistant Director of Cardiac Electrophysiology Research | Acute Care Nurse Practitioner; CEO & Founder; Electrophysiology Nurse Practitioner; Director of Remote andAMbulatory Monitoring | Professor of Medicine; Cardiac Electrophysiology Nurse Practitioner; Nurse Manager of the Cardiac Device Clinic; Cardiac Electrophysiologist, Health Services and Outcomes Researcher, Innovator",
      "session_id": 35,
      "uid": "s_35",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "10:25AM – 10:45AM",
      "room": "Hyde Park",
      "type": "session",
      "Track": "Hot Takes Exchange",
      "Title": "Stroke Prevention in 2030 Will Mostly Be: LAAO vs. Pill-in-the-pocket Anticoagulation",
      "Authors": "Christopher Ellis, Kenneth Ellenbogen",
      "Affiliation": "Vanderbilt University Medical Center; Virginia Commonwealth University | Heart Rhythm Society",
      "SpeakerTitles": "Director LAA (Left Atrial Appendage) Program | Director AF Center; Director of Clinical Cardiac Electrophysiology and Pacing | Kimmerling Chair of Cardiology | President",
      "session_id": 36,
      "uid": "s_36",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "10:45AM – 11:30AM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Pioneering the Future: Integrating ASCs into Cardiovascular Practice and Innovation",
      "Authors": "Arash Aryana, Malcolm Finlay, Dhanunjaya R. Lakkireddy, Christopher Liu, Rohit Mehta, Jodie Hurwitz",
      "Affiliation": "Mercy General Hospital; Barts Heart Centre | Echopoint Medical Ltd | Rhythm AI Ltd; HCA Midwest in Overland Park, Kansas; Weill Cornell Medicine System | New York-Presbyterian Hospital; Sanger Heart and Vascular Institute; North Texas Heart Center",
      "SpeakerTitles": "Cardiac Electrophysiologist & Medical Director; Consultant Cardiologist | Chief Medical Officer | Founder; Executive Medical Director of the Kansas City Heart Rhythm Institute; Director of EP Services; Cardiac Electrophysiologist; Cardiac Electrophysiologist & Partner",
      "session_id": 37,
      "uid": "s_37",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "10:45AM – 11:30AM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Matching the Monitoring Tool to the Clinical Question: Software-Led ECG Analytics in Practice – Powered by AccurKardia",
      "Authors": "Kenneth Civello, Joshua Lampert, Jennifer Peña, Christian Sohns, Natalia Trayanova, PhD, FHRS, Manish Wadhwa, Nicholas Peters",
      "Affiliation": "Suture Health Inc. | Our Lady of the Lake; Mount Sinai Heart in The Mount Sinai Hospital; Medicina Exclusiva; Herz und Diabeteszentrum NRW; Johns Hopkins University; SummaCor | San Diego Arrhythmia Associates | Implicity; Imperial College, Department of Cardiology",
      "SpeakerTitles": "Co-Founder & Chief Medical Officer | Cardiac Electrophysiologist; Cardiac Electrophysiologist & Medical Director of Machine Learning; Founder; Professor of Cardiology | Deputy Director of the Clinic for Electrophysiology and Rhythmology; Professor | Director for AI Research; Chief Executive Officer | Cardiac Electrophysiologist | Medical Advisor; Professor of Cardiac Electrophysiology",
      "session_id": 38,
      "uid": "s_38",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "10:45AM – 11:30AM",
      "room": "Main Stage 2",
      "type": "session",
      "Track": "Session",
      "Title": "Future of Drug Delivery in EP: Pills are So Yesterday",
      "Authors": "David Bharucha, Neal Bhatia, Shilpi Epstein, James Ip, Kristen Bova Campbell",
      "Affiliation": "Milestone Pharmaceuticals, Inc.; Emory University Hospital System; Bayer; Weill Cornell Medicine; Duke University Medical Center",
      "SpeakerTitles": "Chief Medical Officer; Cardiac Electrophysiologist | Co-Director of the Complex Ventricular Tachycardia Ablation Program; Global Clinical Lead, Cardiovascular Clinical Development; Professor; Clinical Pharmacy Specialist and Senior Research Associate in Electrophysiology",
      "session_id": 39,
      "uid": "s_39",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "10:45AM – 11:30AM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Hidden in Plain Sight: Earlier Detection of HFpEF and CardiacAMyloidosis to Improve AF Ablation and LAAC Outcomes – Powered by Ultromics",
      "Authors": "Nazem Akoum, Tina Baykaner, MD, MPH, Robert Kowal, Roger Owens, Michael Raccuglia, T. Jared Bunch",
      "Affiliation": "University of Washington; Department of Internal Medicine | Division of Cardiovascular Medicine and Electrophysiology | Stanford University; Medtronic; Ultromics, Inc.; US Food & Drug Administration; Division of Cardiovascular Medicine at University of Utah Hospital",
      "SpeakerTitles": "Professor of Medicine; Assistant Professor; Vice President and General Manager, Cardiac Pacing Therapies | Cardiac Electrophysiologist; Chief Commercial Officer, Ultromics, Inc.; Biomedical Engineer | Lead Reviewer; Associate Chief of Cardiology",
      "session_id": 40,
      "uid": "s_40",
      "isMedtronic": true
    },
    {
      "day": "Saturday 9/19",
      "time": "10:45AM – 12:20PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "HRX AP Shark Tank",
      "Title": "HRX AP Shark Tank – Powered by Medtronic",
      "Authors": "Kelly Bergen, Hannah Eunice Esmeralda, Vanessa Rhodes, Yekaterina Spivak, Aimee Stefanski, Brynn Dechert-Crooks, Jeroen Hendriks, PhD, RN",
      "Affiliation": "CaroMont Health; Virginia Mason Franciscan Health; Cardiac Solutions; Children’s Hospital of Philadelphia | Welcome Baby 247; Yale New Haven Health System; University of Michigan Congenital Heart Center; Centre for Heart Rhythm Disorders, University of Adelaide",
      "SpeakerTitles": "Electrophysiology Acute Care Nurse Practitioner; Advanced Practice Nurse; Acute Care Nurse Practitioner; Pediatric Electrophysiology Physician Assistant | IBCLC & Co-founder; Nurse Practitioner; Pediatric Electrophysiology Nurse Practitioner; Professor of Cardiovascular Nursing",
      "session_id": 41,
      "uid": "s_41",
      "isMedtronic": true
    },
    {
      "day": "Saturday 9/19",
      "time": "11:35AM – 12:20PM",
      "room": "Main Stage 2",
      "type": "session",
      "Track": "Session",
      "Title": "Autonomous and Assistive EP Procedural Systems",
      "Authors": "Jim Cheung, David Fischel, Katherine Lindborg, Sanjiv Narayan, Jennifer N. Avari Silva, J. Peter Weiss",
      "Affiliation": "Weill Cornell Medicine; Stereotaxis; Imricor Medical Systems; Stanford University; SentiAR, Inc. | Washington University in St. Louis; Banner University of Arizona Medical Center Phoenix (BUMCP)",
      "SpeakerTitles": "Professor of Medicine; Chairman & CEO; Vice President of Clinical Affairs; Professor of Medicine | Director of the NIH T32 Computational Medicine Training Program (CHIP) | Co-Director of the Arrhythmia Center; Co-Founder & CMO | Associate Professor & Director of Pediatric Electrophysiology; Cardiac Electrophysiologist",
      "session_id": 42,
      "uid": "s_42",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "11:35AM – 12:20PM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Beyond Comorbidity: Integrating AF and Heart Failure Management – Powered by Medtronic",
      "Authors": "Chad Bonhomme, Godefroy Chery, Zhaohui Qiu, Joshua Silverstein, Christian Sohns, Andrea Swain, T. Jared Bunch",
      "Affiliation": "Westfield Physician Holdings, LLC; Penn Medicine, University of Pennsylvania Health System; Shanghai Jiao Tong University School of Medicine; Allegheny Health Network; Herz und Diabeteszentrum NRW; Medtronic; Division of Cardiovascular Medicine at University of Utah Hospital",
      "SpeakerTitles": "President & Electrophysiologist; EP Fellow; Director of Cardiology; Cardiac Electrophysiologist; Professor of Cardiology | Deputy Director of the Clinic for Electrophysiology and Rhythmology; VP, General Manager; Associate Chief of Cardiology",
      "session_id": 43,
      "uid": "s_43",
      "isMedtronic": true
    },
    {
      "day": "Saturday 9/19",
      "time": "11:35AM – 12:20PM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Closing the Gaps in Cardiac Remote Monitoring – Patient Engagement, Connectivity, and Compliance – Powered by CardiacRMS",
      "Authors": "Nashwa Abdulsalam, Sana Al-Khatib, Tamara Bazar, Daniel Frenkel,AMy Tucker, Kamala Tamirisa, Thomas Deering",
      "Affiliation": "PeaceHealth Southwest Medical Center | Heart Rhythm O2; Duke University; Cardiac RMS by DocGo; Westchester Medical Center; Sanger Heart & Vascular Institute (SHVI); UT Southwestern Medical Center; Piedmont Heart Institute",
      "SpeakerTitles": "Cardiac Electrophysiologist | Social Media Editor; Professor of Medicine at Duke University | Cardiac Electrophysiologist; Co Founder & Managing Partner; Cardiac Electrophysiologist; Nurse Manager of the Cardiac Device Clinic; Clinical Cardiac Electrophysiologist | Associate Professor of Internal Medicine in the Division of Cardiology | Director of Electrophysiology Research; Chief, Cardiovascular Centers of Excellence | Chief, Arrhythmia Center",
      "session_id": 44,
      "uid": "s_44",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "11:35AM – 12:20PM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "The Future of Post-PFA Care: Improving Outcomes Through Continuous Monitoring and AI Insights – Powered by Zywie",
      "Authors": "Edward Gerstenfeld, Melanie Gunawardene, Nino Isakadze, Krishna Pundi, Elaine Wan, Steven L. Zweibel, Paul Zei",
      "Affiliation": "University of California, San Francisco; CCB Frankfurt; Johns Hopkins Hospital; Palo Alto VA Hospital; Columbia University Medical Center, College of Physicians and Surgeons | New York-Presbyterian Hospital; Hartford HealthCare Heart & Vascular Institute; Brigham and Women’s Hospital",
      "SpeakerTitles": "Professor of Medicine; Senior Cardiac Electrophysiologist; Assistant Professor of Medicine | Cardiac Electrophysiologist; Cardiac Electrophysiologist, Health Services and Outcomes Researcher, Innovator; Esther Aboodi Associate Professor of Medicine in Cardiology and Cardiac Electrophysiology | Attending Physician at New York-Presbyterian Hospital; Medical Director of Innovation; Cardiac Electrophysiologist",
      "session_id": 45,
      "uid": "s_45",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "12:20PM – 12:40PM",
      "room": "Hyde Park",
      "type": "session",
      "Track": "Hot Takes Exchange",
      "Title": "Site-less Clinical Trials are the Future of Research",
      "Authors": "Gregory Marcus, Valentina Kutyifa, Jose Osorio",
      "Affiliation": "Univ of California, San Francisco | JAMA; University of Rochester Medical Center; HCA Florida Miami | 3PH Alliance | Heart Rhythm Clinical Research Solutions",
      "SpeakerTitles": "Cardiac Electrophysiologist & Professor of Medicine | Associate Chief of Cardiology for Research; Professor of Medicine; Medical Director of Electrophysiology – HCA Florida Miami |  Founder and CMO | Founder and President",
      "session_id": 46,
      "uid": "s_46",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "12:30PM – 01:10PM",
      "room": "Abstract Happy Hour – Main Stage 1, Main Stage 2, Roundtable 1, Roundtable 2, Roundtable 3, ConneXions Lounge",
      "type": "session",
      "Track": "Abstract Lunch Hour",
      "Title": "HRX Abstract Lunch Hour",
      "Authors": "Leart Ajvazaj, Yong-Soo Baek, Rami Bailony, Revanth Reddy Bandaru, Andreu Climent, Kristie Coleman, Ricardo De Armas, Derek Exner, Han Feng, Salomón Giraldo, MD, Christopher Harvey, Jason T. Jacobson, MD, FHRS, Prapa Kanagaratnam, Josef Kautzner, Matthew S. McKillop, Stavros Mountantonakis, Rachita Navara, Sivaranjini Perikamana Narayanan, Zain Shariff, Ana Sopa, Jomole Varghese Vadakkan, Anand Ganesan, Rakesh Gopinathannair, Robin Leahy, Deepthy Varghese, Nicholas Von Bergen",
      "Affiliation": "91Life; Division Cardiology, Inha University College of Medicine and Inha U Hospital; Enara Health; USF Morsani College of Medicine/HCA Florida Citrus Hospital; Corify Care; Lenox Hill Hospital; MontiAir; HelpWear Inc. | Cumming School of Medicine at University of Calgary; Tulane University School of Medicine; Las Palmas Medical Centers; University of Kansas; New York Medical College-Westchester Medical Center; Imperial College Healthcare, St Mary’s Hospital, Cardiology; IKEM Prague; Baptist Health System, Jacksonville; SafeBeat﻿ Rx; Indian Institute of Technology Palakkad; AICathDesigner | Curtis Senior High School; Indian Institute of Technology Palakkad, Kerala, India; Flinders Medical Centre | Flinders University; Kansas City Heart Rhythm Institute; PaceMate; Emory University Hospital; University of Wisconsin-Madison | Atrility Medical, LLC",
      "SpeakerTitles": "Head of Artificial Intelligence; Associate Professor; CEO and Co-Founder; Cardiology Fellow; CEO & Co-Founder; Director, Cardiac Electrophysiology Research; Founder; Chief Medical Officer | Professor; Assistant Professor; Clinical Rotation | Internal Medicine; Machine Learning Researcher; Cardiac Electrophysiologist; Consultant Cardiologist; Cardiac Electrophysiologist | Director of the Heart Centre and Head of Department of Cardiology; Medical Director, Clinical Cardiac Electrophysiology; Director, Clinical Electrophysiology; Co-founder & CEO of SafeBeat﻿ (YC S21) | EP Cardiologist | Engineer | NIH-funded Principal Investigator; PhD Research Scholar; Creator | Student; Machine Learning Engineer; Research Scholar; Director of Cardiac Electrophysiology | Professor of Medicine; Director of Cardiac Electrophysiology Laboratories; Vice President of Clinical Affairs; Electrophysiology Nurse Practitioner; Professor of Pediatrics in Pediatric Cardiac Electrophysiologist | Co-Founder",
      "session_id": 47,
      "uid": "s_47",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "01:00PM – 01:20PM",
      "room": "Hyde Park",
      "type": "session",
      "Track": "Hot Takes Exchange",
      "Title": "VT Ablation Will Render the ICD Obsolete Within 10 Years",
      "Authors": "Gerhard Hindricks, MD, PhD, Jeanne Poole, Nikolaos Dagres",
      "Affiliation": "Charite University Hospital, Berlin; University of Washington Medical Center and School of Medicine; Deutsches Herzzentrum der Charite",
      "SpeakerTitles": "Medical Director; Cardiac Electrophysiologist | Director | Professor of Cardiology and Medicine; Cardiac Electrophysiologist",
      "session_id": 48,
      "uid": "s_48",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "01:10PM – 01:20PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "General",
      "Title": "Interventional MR is Here: How to Launch Your Program, Powered by Imricor",
      "Authors": "Kenneth Bilchick",
      "Affiliation": "University of Virginia",
      "SpeakerTitles": "Associate Professor of Medicine | Clinical Cardiologist & Electrophysiologist",
      "session_id": 49,
      "uid": "s_49",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "01:20PM – 02:05PM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Innovation in Signal Detection forAMbulatory ECG Monitoring – Powered by Baxter",
      "Authors": "Adrian Elliott, Anne Kroman, Christopher Liu, Deepak Padmanabhan, Miguel Valderrabano, Deepthy Varghese, Jodie Hurwitz",
      "Affiliation": "Adelaide University, Royal Adelaide Hospital; Medical University of South Carolina; Weill Cornell Medicine System | New York-Presbyterian Hospital; Sri Jayadeva Institute of Cardiovascular Sciences and Research; Division of Cardiac Electrophysiology at The Methodist Hospital; Emory University Hospital; North Texas Heart Center",
      "SpeakerTitles": "Senior Research Fellow | Associate Professor; Associate Professor of Cardiac Electrophysiology | Director of the Lead Management Program, the Cardiac Device Clinic, and MUSC Heart Station; Director of EP Services; Assistant Professor; Director; Electrophysiology Nurse Practitioner; Cardiac Electrophysiologist & Partner",
      "session_id": 50,
      "uid": "s_50",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "01:20PM – 02:05PM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Low Risk or High Stakes? Navigating AF Alerts From Consumer Devices in Everyday Practice – Powered by Boston Scientific",
      "Authors": "Sana Al-Khatib, Jason Andrade, Jon Crane, Tony Fiola, Jason T. Jacobson, MD, FHRS, Melissa Middeldorp, Ajay Naik, Thomas Deering",
      "Affiliation": "Duke University; Vancouver General Hospital; Piedmont Heart Institute; Global Cardiac Diagnostic Services Franchise at Boston Scientific; New York Medical College-Westchester Medical Center; Adelaide University; Marengo CIMS Hospital, Care Institute of Medical Sciences",
      "SpeakerTitles": "Professor of Medicine at Duke University | Cardiac Electrophysiologist; Cardiac Electrophysiologist & Director of Electrophysiology; Vice President; Vice President & General Manager; Cardiac Electrophysiologist; Clinical Researcher; Cardiac Electrophysiologist; Chief, Cardiovascular Centers of Excellence | Chief, Arrhythmia Center",
      "session_id": 51,
      "uid": "s_51",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "01:20PM – 02:05PM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Building the Intelligent Cardiology Platform – Bringing together devices, EMRs, remote monitoring, AI, and patient engagement into a unified ecosystem – Powered by 91Life",
      "Authors": "Tamara Bazar, Eric Grubman, Ardi Jusufi, Signe Risom, Heather Ross, Benjamin Steinberg, Aimee Stefanski",
      "Affiliation": "Cardiac RMS by DocGo; Yale University School of Medicine; 91Life; Herlev og Gentofte Hospital | Københavns Universitet – University of Copenhagen; Arizona State University; Denver Health Medical Center; Yale New Haven Health System",
      "SpeakerTitles": "Co Founder & Managing Partner; Cardiac Electrophysiologist; Chief Product Officer; Nurse and Senior Researcher | Associate Professor; Assistant Professor | Nurse Practitioner; Director of Cardiac Electrophysiology; Nurse Practitioner",
      "session_id": 52,
      "uid": "s_52",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "01:30PM – 02:50PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Pitch Competition",
      "Title": "Pitch Competition II",
      "Authors": "Tal Avziz, Adarsh Balaji, Andrew Bank, Darryl Davis, Hirohiko Kohjitani",
      "Affiliation": "Vibrant Medical; New York Presbyterian Brooklyn Methodist; Myochron; University of Ottawa Heart Institute; Kyoto University Hospital",
      "SpeakerTitles": "CEO & Co-Founder; Cardiovascular Disease Fellow; CEO & Co-Founder; Clinician Scientist; Lecturer | Medical Doctor",
      "session_id": 53,
      "uid": "s_53",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "02:10PM – 02:55PM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "The Next Frontier of Cardiac Mapping – Powered by Johnson & Johnson MedTech",
      "Authors": "Rodolfo Estay, Larry Jackson, II, David Krummen, Sanjiv Narayan, Natalia Trayanova, PhD, FHRS, Jose Osorio",
      "Affiliation": "Johnson & Johnson MedTech | SLG Med Consulting; Duke University Medical Center; University of California San Diego; Stanford University; Johns Hopkins University; HCA Florida Miami | 3PH Alliance | Heart Rhythm Clinical Research Solutions",
      "SpeakerTitles": "Vice President, Global Strategic Marketing | Managing Principal & Founder; Associate Professor of Medicine; Professor of Clinical Medicine; Professor of Medicine | Director of the NIH T32 Computational Medicine Training Program (CHIP) | Co-Director of the Arrhythmia Center; Professor | Director for AI Research; Medical Director of Electrophysiology – HCA Florida Miami |  Founder and CMO | Founder and President",
      "session_id": 54,
      "uid": "s_54",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "02:10PM – 02:55PM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Beyond the ECG: Building the Future of Cardiovascular AI withAMbulatory Monitoring Data – Powered by Philips",
      "Authors": "Hamid Ghanbari, Matthew Kalscheur, Valentina Kutyifa, Joshua Lampert, Ian Lentnek, John Triedman, Paul Varosy, David Ludwig",
      "Affiliation": "University of Michigan Cardiovascular Center; University of Wisconsin School of Medicine and Public Health; University of Rochester Medical Center; Mount Sinai Heart in The Mount Sinai Hospital; Philips; Harvard Medical School | Boston Children’s Hospital; VA Eastern Colorado Health Care System | University of Colorado School of Medicine | Veterans Health Administration Cardiology",
      "SpeakerTitles": "Chair of Innovation, Clinical Associate Professor; Cardiac Electrophysiologist & Clinical Informaticist; Professor of Medicine; Cardiac Electrophysiologist & Medical Director of Machine Learning; Head of Medical and Clinical forAMbulatory Monitoring and Diagnostics (AM&D); Professor of Pediatrics | Former Chief of Pediatric EP; Director of EP | Professor of Medicine | Deputy National Program Director; Strategic Initiatives Lead, ECG Solutions",
      "session_id": 55,
      "uid": "s_55",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "02:10PM – 02:55PM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Next Generation PFA Waveforms: Competing Visions",
      "Authors": "Edward Gerstenfeld, Melanie Gunawardene, Mélèze Hocini, Jacob Koruth, Steven Mickelsen, Dominik K Linz, MD, PhD",
      "Affiliation": "University of California, San Francisco; CCB Frankfurt; Bordeaux University Hospital’s Cardiac Arrhythmias Center | IHU Liryc; Mount Sinai Medical Center; Field Medical | Atraverse Medical, Inc. | Scripps Health; Maastricht University Medical Center",
      "SpeakerTitles": "Professor of Medicine; Senior Cardiac Electrophysiologist; Professor of Cardiology | Deputy Director; Associate Professor; CEO | Board Member | Cardiac Electrophysiologist; Professor | EP Consultant",
      "session_id": 56,
      "uid": "s_56",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "02:55PM – 03:15PM",
      "room": "Hyde Park",
      "type": "session",
      "Track": "Hot Takes Exchange",
      "Title": "Mapping in AF is a Moonshot",
      "Authors": "Luigi Di Biase, MD, PhD, FHRS, Sanjiv Narayan, Melanie Gunawardene",
      "Affiliation": "Albert Einstein College of Medicine at Montefiore Health System; Stanford University; CCB Frankfurt",
      "SpeakerTitles": "Clinical Cardiac Electrophysiology; Professor of Medicine | Director of the NIH T32 Computational Medicine Training Program (CHIP) | Co-Director of the Arrhythmia Center; Senior Cardiac Electrophysiologist",
      "session_id": 57,
      "uid": "s_57",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "03:15PM – 04:00PM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Orchestrating the Next Generation of Cardiac Care for Device Patients: Optimizing Data Interoperability, Streamlining Workflows, and Enhancing Clinical Signals – Powered by Murj",
      "Authors": "Chris Irving, Matthew Kalscheur, George Stuart Mendenhall, Tracey Shannon, Yekaterina Spivak, Steven L. Zweibel, David Slotwiner",
      "Affiliation": "Murj Inc.; University of Wisconsin School of Medicine and Public Health; Scripps Memorial Hospital | Everbeat; Westchester Medical Center; Children’s Hospital of Philadelphia | Welcome Baby 247; Hartford HealthCare Heart & Vascular Institute; New York Presbyterian Queens",
      "SpeakerTitles": "Co-Founder, Chief Experience Officer & Head of Design; Cardiac Electrophysiologist & Clinical Informaticist; Cardiac Electrophysiologist and Researcher | Chief Medical Officer; Program Coordinator, Electrophysiology; Pediatric Electrophysiology Physician Assistant | IBCLC & Co-founder; Medical Director of Innovation; Chief of the Division of Cardiology",
      "session_id": 58,
      "uid": "s_58",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "03:15PM – 04:00PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Session",
      "Title": "Precision Energy Delivery in EP: Programmable Ablation Platforms",
      "Authors": "Melanie Gunawardene, Jacob Koruth, Steven Mickelsen, Hiroshi Nakagawa, Andrea Sarkozy, Gerhard Hindricks, MD, PhD",
      "Affiliation": "CCB Frankfurt; Mount Sinai Medical Center; Field Medical | Atraverse Medical, Inc. | Scripps Health; Cleveland Clinic; Ventricular Arrhythmia & Sudden Death Unit, UZ Brussel; Charite University Hospital, Berlin",
      "SpeakerTitles": "Senior Cardiac Electrophysiologist; Associate Professor; CEO | Board Member | Cardiac Electrophysiologist; Cardiac Electrophysiologist & Professor; Professor of Cardiology & Free University of Brussels Director; Medical Director",
      "session_id": 59,
      "uid": "s_59",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "03:15PM – 04:00PM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Extended and Augmented Reality: Reshaping the EP Lab, the Workforce, and the Business of Cardiac Ablations – Powered by SentiAR",
      "Authors": "Enrico Ferro, Nassir Marrouche, Anthony Pompa, Usman Siddiqui, Usha Tedrow, Jagmeet Singh",
      "Affiliation": "Harvard Medical School – Beth Israel Deaconess Medical Center | Smith Center for Outcomes Research; Tulane University School of Medicine; Washington University; Advent Health Celebration; Brigham and Women’s Hospital | Harvard Medical School; Harvard Medical School | Massachusetts General Hospital Heart Center",
      "SpeakerTitles": "Electrophysiologist | Clinical Investigator; Director of Heart and Vascular Institute; Pediatric Electrophysiologist; Electrophysiologist; Director, Clinical Cardiac Electrophysiology Program | Associate Professor of Medicine; Professor of Medicine | Cardiac Electrophysiologist & Founding Director of the Resynchronization and Advanced Cardiac Therapeutics Program",
      "session_id": 60,
      "uid": "s_60",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "03:15PM – 04:00PM",
      "room": "Main Stage 2",
      "type": "session",
      "Track": "Session",
      "Title": "Leveraging New Technology to Expand Access to Arrhythmia Care in Underserved Populations",
      "Authors": "Simon Henley, Geraldine Lee, Melissa Middeldorp, Michael Raccuglia, Heather Ross, Deepthy Varghese, Jeroen Hendriks, PhD, RN",
      "Affiliation": "Medtronic; University College Cork; Adelaide University; US Food & Drug Administration; Arizona State University; Emory University Hospital; Centre for Heart Rhythm Disorders, University of Adelaide",
      "SpeakerTitles": "Director, HF Market Development – Cardiac Rhythm Management; Professor of Nursing; Clinical Researcher; Biomedical Engineer | Lead Reviewer; Assistant Professor | Nurse Practitioner; Electrophysiology Nurse Practitioner; Professor of Cardiovascular Nursing",
      "session_id": 61,
      "uid": "s_61",
      "isMedtronic": true
    },
    {
      "day": "Saturday 9/19",
      "time": "03:15PM – 04:00PM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Digital Twins in EP: Can Computational Models Guide Real Therapy?",
      "Authors": "Jonathan Chrispin, Anand Ganesan, Tanmay Gokhale, Luke Ralston, Natalia Trayanova, PhD, FHRS, Jeffrey Winterfield, Patrick Boyle",
      "Affiliation": "Johns Hopkins University School of Medicine; Flinders Medical Centre | Flinders University; University of Pittsburgh Medical Center; US Food & Drug Administration; Johns Hopkins University; Medical University of South Carolina; University of Washington",
      "SpeakerTitles": "Associate Professor of Medicine; Associate Professor of Biomedical Engineering; Director of the Ventricular Arrhythmia Ablation Program; Director of Cardiac Electrophysiology | Professor of Medicine; Cardiac Electrophysiology Fellow; Biomedical Engineer; Professor | Director for AI Research; Hank and Laurel Greer Chair in Clinical Cardiac Electrophysiology | Professor of Medicine; Associate Professor of Bioengineering",
      "session_id": 62,
      "uid": "s_62",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "04:05PM – 04:50PM",
      "room": "Main Stage 2",
      "type": "session",
      "Track": "Session",
      "Title": "Nanoparticle Therapies in EP",
      "Authors": "Igor R. Efimov, Natalia Trayanova, PhD, FHRS, Miguel Valderrabano, Patrick Boyle",
      "Affiliation": "Northwestern University; Johns Hopkins University; Division of Cardiac Electrophysiology at The Methodist Hospital; University of Washington",
      "SpeakerTitles": "Professor of Biomedical Engineering & Professor of Medicine; Professor | Director for AI Research; Director; Associate Professor of Bioengineering",
      "session_id": 63,
      "uid": "s_63",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "04:05PM – 04:50PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Session",
      "Title": "Leadless Pacing – Act II",
      "Authors": "Daniel Cantillon, Christophe Garweg, Deepak Padmanabhan, Vivek Y. Reddy, Mikhael El-Chami",
      "Affiliation": "Masimo Corporation; UZ Leuven; Sri Jayadeva Institute of Cardiovascular Sciences and Research; Mount Sinai Health System; Emory University",
      "SpeakerTitles": "Adult EP Cardiologist & Chief Medical Officer; Associate Professor & Cardiologist; Assistant Professor; Director of Cardiac Arrhythmia Services; Electrophysiologist | Professor of Medicine",
      "session_id": 64,
      "uid": "s_64",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "04:05PM – 04:50PM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Should AI Make the Call? Decision Algorithms Under Debate",
      "Authors": "Kristen Bova Campbell, Geraldine Lee, Alanna Miller, Deepthy Varghese, Erica Zado, PAC, FHRS, Lisa Roelle",
      "Affiliation": "Duke University Medical Center; University College Cork; Penn Presbyterian Medical Center; Emory University Hospital; Hospital of the University of Pennsylvania; Washington University in St. Louis & St. Louis Children’s Hospital",
      "SpeakerTitles": "Clinical Pharmacy Specialist and Senior Research Associate in Electrophysiology; Professor of Nursing; Lead Advanced Practitioner, Cardiac Electrophysiology; Electrophysiology Nurse Practitioner; Physician Assistant; Pediatric Electrophysiology Physician Assistant",
      "session_id": 65,
      "uid": "s_65",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "04:05PM – 04:50PM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Innovating with Care: The Connected Heart of Responsible Innovation and Data Interoperability – Powered by RhythmScience",
      "Authors": "Brynn Dechert-Crooks, Shawn Kumar, Michael Lloyd, Kalyanam Shivkumar, David Slotwiner, Kenneth Civello",
      "Affiliation": "University of Michigan Congenital Heart Center; Rhythm Science; Emory University; UCLA Health System, UCLA Cardiac Arrhythmia Center & EP Programs; New York Presbyterian Queens; Suture Health Inc. | Our Lady of the Lake",
      "SpeakerTitles": "Pediatric Electrophysiology Nurse Practitioner; Founder | CEO; Director of EP Laboratories | Professor of Medicine | Cardiac Electrophysiologist; Professor & Director, Center for Interventional Programs; Chief of the Division of Cardiology; Co-Founder & Chief Medical Officer | Cardiac Electrophysiologist",
      "session_id": 66,
      "uid": "s_66",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "04:05PM – 04:50PM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Cardiac Monitoring – Tools, Technology, Tradeoffs, and Trust – Powered by iRhythm",
      "Authors": "Jason Andrade, Mina K. Chung, Janet K. Han, Krishna Pundi, Mintu Turakhia, Paul Zei, T. Jared Bunch",
      "Affiliation": "Vancouver General Hospital; Cleveland Clinic; UCLA | VA Greater Los Angeles Healthcare System / UCLA | Digital Health & Virtual Care; Palo Alto VA Hospital; iRhythm Technologies, Inc. | Stanford University; Brigham and Women’s Hospital; Division of Cardiovascular Medicine at University of Utah Hospital",
      "SpeakerTitles": "Cardiac Electrophysiologist & Director of Electrophysiology; Staff Cardiologist & Professor of Medicine in the Section of Pacing and Electrophysiology; Associate Professor of Medicine | Cardiac Electrophysiology; Cardiac Electrophysiologist, Health Services and Outcomes Researcher, Innovator; Chief Medical and Scientific Officer + EVP, Product Management and Innovation | Professor of Medicine and Cardiac Electrophysiologist; Cardiac Electrophysiologist; Associate Chief of Cardiology",
      "session_id": 67,
      "uid": "s_67",
      "isMedtronic": false
    },
    {
      "day": "Saturday 9/19",
      "time": "04:50PM – 05:00PM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "General",
      "Title": "AP Shark Tank & Pitch Competition Winner Announcement",
      "Authors": "Brynn Dechert-Crooks, Jeroen Hendriks, PhD, RN, Robert Kowal, Mintu Turakhia, Jonathan Piccini, Prashanthan Sanders",
      "Affiliation": "University of Michigan Congenital Heart Center; Centre for Heart Rhythm Disorders, University of Adelaide; Medtronic; iRhythm Technologies, Inc. | Stanford University; Duke University Hospital and the Duke Clinical Research Institute | Duke Heart Center; University of Adelaide",
      "SpeakerTitles": "Pediatric Electrophysiology Nurse Practitioner; Professor of Cardiovascular Nursing; Vice President and General Manager, Cardiac Pacing Therapies | Cardiac Electrophysiologist; Chief Medical and Scientific Officer + EVP, Product Management and Innovation | Professor of Medicine and Cardiac Electrophysiologist; Cardiac Electrophysiologist & Professor of Medicine and Population Health | Director of the Cardiac Electrophysiology section; Cardiac Electrophysiologist & Director of Cardiac Electrophysiology",
      "session_id": 68,
      "uid": "s_68",
      "isMedtronic": true
    },
    {
      "day": "Saturday 9/19",
      "time": "05:00PM – 06:30PM",
      "room": "Abstract Happy Hour – Main Stage 1, Main Stage 2, Roundtable 1, Roundtable 2, Roundtable 3, ConneXions Lounge",
      "type": "session",
      "Track": "Abstract Happy Hour",
      "Title": "HRX Abstract Happy Hour II",
      "Authors": "Michel Abou Khalil, Faraz Ahmad, Leart Ajvazaj, Manav Bhushan, Kashif Chaudhry, Ashley Cooper, Jordan Craig, Jacob Cushing, Michiel De Wever, Alex El Darzi, Shaun Evans, Derek Exner, Sanjaya Gupta, Yaariv Khaykin, Jonathan Lipton, Yingshuo Liu, Christian Massad, Yazan Mohsen, Daniel Musikantow, Alexei Nakonechnyi, Anthony Pompa, Lisa Roelle, Uttsav Sandesara, Kavya Sinha, Raghav Sriram, Ajay Tripuraneni, Gaurav Upadhyay, Jomole Varghese Vadakkan, Rohan Viswanathan, Tae Kyung Yoo, Apo Youssef, Yuanyuan Zhang, Thomas Deering, Nassir Marrouche, Jennifer N. Avari Silva, Konstantinos Siontis, MD, FHRS, Benjamin Steinberg, Emma Svennberg, MD, PhD",
      "Affiliation": "Tulane Research Innovation for Arrhythmia Discovery (TRIAD); Northwestern Medicine; 91Life; Fourth Frontier; Catawba Valley Medical Center; Washington University School of Medicine in St. Louis; Boston Scientific; University of Kansas Medical Center; Ziekenhuis Oost Limburg; TRIAD-Tulane University; Centre for Heart Rhythm Disorders in Adelaide; HelpWear Inc. | Cumming School of Medicine at University of Calgary; Saint Luke’s Mid-America Heart Institute; Myant Health; Fiona Stanley Hospital; Tulane University School of Medicine; TRIAD; Johns Hopkins University; Mount Sinai Hospital; University of Rochester; Washington University; Washington University in St. Louis & St. Louis Children’s Hospital; Wake Forest Baptist Medical Center; Texas Heart Institute at Baylor College of Medicine; University of Michigan; Baylor Scott & White Health; The University of Chicago Medicine; Indian Institute of Technology Palakkad, Kerala, India; Deborah Heart and Lung Center; Boston Medical Center; Valley Health System – ISMMS; University of Georgia; Piedmont Heart Institute; SentiAR, Inc. | Washington University in St. Louis; Mayo Clinic; Denver Health Medical Center; Karolinska University Hospital",
      "SpeakerTitles": "Medical Intern & Research Fellow; Medical Director for AI Strategy, Bluhm Cardiovascular Center for AI; Head of Artificial Intelligence; CEO & Co-Founder; Director, Cardiac Electrophysiology; Clinical Research Study Assistant; Principal Data Scientist; Internal Medicine Resident; PhD researcher; Cardiology Post-Doc; Electrophysiology Fellow & PhD Candidate; Chief Medical Officer | Professor; Electrophysiologist; Chief Medical Information Officer; Cardiologist Electrophysiologist; Biostatistician; Research Fellow; Research Scientist; Cardiac Electrophysiologist; Research Assistant Professor; Pediatric Electrophysiologist; Pediatric Electrophysiology Physician Assistant; Cardiovascular Disease Fellow; Assistant Professor of Cardiovascular Science; Researcher; Cardiac Electrophysiologist; Professor of Medicine; Research Scholar; Cardiology Fellow; Cardiology Fellow; PGY-2 Internal Medicine Resident; Postdoctoral Associate; Chief, Cardiovascular Centers of Excellence | Chief, Arrhythmia Center; Director of Heart and Vascular Institute; Co-Founder & CMO | Associate Professor & Director of Pediatric Electrophysiology; Cardiac Electrophysiologist | Assistant Professor of Medicine at Mayo Clinic | Director of the Cardiac Radioablation; Director of Cardiac Electrophysiology; Assistant professor | Electrophysiologist",
      "session_id": 69,
      "uid": "s_69",
      "isMedtronic": false
    }
  ],
  "Sunday 9/20": [
    {
      "day": "Sunday 9/20",
      "time": "07:50AM – 08:00AM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "General",
      "Title": "Sunday Opening Remarks",
      "Authors": "Jonathan Piccini, Prashanthan Sanders",
      "Affiliation": "Duke University Hospital and the Duke Clinical Research Institute | Duke Heart Center; University of Adelaide",
      "SpeakerTitles": "Cardiac Electrophysiologist & Professor of Medicine and Population Health | Director of the Cardiac Electrophysiology section; Cardiac Electrophysiologist & Director of Cardiac Electrophysiology",
      "session_id": 70,
      "uid": "s_70",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "08:00AM – 08:45AM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Featured Keynote",
      "Title": "The Spark That Changed Electrophysiology: Discovery, Disruption, and the Future of Arrhythmia Care",
      "Authors": "Michel Haissaguerre, Prashanthan Sanders",
      "Affiliation": "CHU Bordeaux; University of Adelaide",
      "SpeakerTitles": "Cardiac Electrophysiologist & Professor; Cardiac Electrophysiologist & Director of Cardiac Electrophysiology",
      "session_id": 71,
      "uid": "s_71",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "08:45AM – 09:30AM",
      "room": "Main Stage 2",
      "type": "session",
      "Track": "Session",
      "Title": "Latent Intelligence and Patient Needs: Clinical Judgment in AI-Driven Electrophysiology",
      "Authors": "Bleron Baraliu, Zak Loring, Ivan Nenadic Wood, Peter Noseworthy, Natalia Trayanova, PhD, FHRS, Joshua Lampert",
      "Affiliation": "91Life; Duke University Medical Center; Duke University Health System; Mayo Clinic; Johns Hopkins University; Mount Sinai Heart in The Mount Sinai Hospital",
      "SpeakerTitles": "CEO; Cardiac Electrophysiologist; Cardiology Fellow, Professor of Biomedical Engineering, Medical Technology Consultant; Professor of Medicine, Chair of the Division of Heart Rhythm Services, and Medical Director of Business Development; Professor | Director for AI Research; Cardiac Electrophysiologist & Medical Director of Machine Learning",
      "session_id": 72,
      "uid": "s_72",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "08:45AM – 09:30AM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "What Does a Fully Connected EP Lab Look Like? Bridging Data, Imaging, and Workflow in Complex Ablation – Powered by Siemens Healthineers",
      "Authors": "Michael Lloyd, Suneet Mittal, Babak Nazer, Miguel Valderrabano, Jennifer N. Avari Silva",
      "Affiliation": "Emory University; Valley Health System; University of Washington; Division of Cardiac Electrophysiology at The Methodist Hospital; SentiAR, Inc. | Washington University in St. Louis",
      "SpeakerTitles": "Director of EP Laboratories | Professor of Medicine | Cardiac Electrophysiologist; Chair, Cardiovascular Service Line; Professor of Medicine and Bioengineering | Cardiac Electrophysiologist; Director; Co-Founder & CMO | Associate Professor & Director of Pediatric Electrophysiology",
      "session_id": 73,
      "uid": "s_73",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "08:45AM – 09:30AM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Session",
      "Title": "Next Generation Mediastinal and Epicardial Technologies & Techniques",
      "Authors": "Ed Manicka, Kalyanam Shivkumar, Usha Tedrow, Venkatakrishna Tholakanahalli, Harikrishna Tandri",
      "Affiliation": "Calyan Technolgies, Inc.; UCLA Health System, UCLA Cardiac Arrhythmia Center & EP Programs; Brigham and Women’s Hospital | Harvard Medical School; University of Minnesota | Minneapolis VA Health Care System; Vanderbilt University Medical Center",
      "SpeakerTitles": "Founder; Professor & Director, Center for Interventional Programs; Director, Clinical Cardiac Electrophysiology Program | Associate Professor of Medicine; Professor of Medicine | Chief-Cardiac Electrophysiology; Professor of Medicine; Chief of Electrophsyiology",
      "session_id": 74,
      "uid": "s_74",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "08:45AM – 09:30AM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Changing How We Predict, Prevent, and Treat Sudden Cardiac Arrest",
      "Authors": "Alan Cheng, Mina K. Chung, Rakesh Gopinathannair, Richard Price, Luke Ralston, Konstantinos Siontis, MD, FHRS, Brianna Wolfe, Mehak Dhande",
      "Affiliation": "Medtronic; Cleveland Clinic; Kansas City Heart Rhythm Institute; PulsePoint Foundation; US Food & Drug Administration; Mayo Clinic; Georgia Arrhythmia Consultants and Research Institute | Georgia Arrhythmia Foundation & S.C.A.R.E; Stanford University, Stanford Healthcare",
      "SpeakerTitles": "Chief Medical Officer of the Medtronic Cardiac Rhythm Management Operating Unit; Staff Cardiologist & Professor of Medicine in the Section of Pacing and Electrophysiology; Director of Cardiac Electrophysiology Laboratories; Founder &  President; Biomedical Engineer; Cardiac Electrophysiologist | Assistant Professor of Medicine at Mayo Clinic | Director of the Cardiac Radioablation; Clinical Exercise Physiologist and Director of Operations | Executive Director; Interventional Cardiac Electrophysiologist | Physician Scientist",
      "session_id": 75,
      "uid": "s_75",
      "isMedtronic": true
    },
    {
      "day": "Sunday 9/20",
      "time": "08:45AM – 09:30AM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Next Generation Stroke Prevention: Factor XI Inhibition in Atrial Fibrillation – Powered by BMS/J&J Alliance",
      "Authors": "Kristen Bova Campbell, Jeffrey Healey, William McIntyre, MD, PhD, FRCPC, Rod Passman, Benjamin Steinberg",
      "Affiliation": "Duke University Medical Center; McMaster University; St Joseph’s Healthcare Hamilton; Northwestern University Feinberg School of Medicine; Denver Health Medical Center",
      "SpeakerTitles": "Clinical Pharmacy Specialist and Senior Research Associate in Electrophysiology; Professor | Director, Division of Cardiology; Cardiologist | Assistant Professor; Jules Reingold Professor of Electrophysiology & Cardiac Electrophysiologist; Director of Cardiac Electrophysiology",
      "session_id": 76,
      "uid": "s_76",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "09:35AM – 10:35AM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Late-Breaking Clinical Trial",
      "Title": "Late-Breaking Clinical Trials: Advances in Pacing, Cardiac Rhythm Devices & Digital Care",
      "Authors": "Minglong Chen, Edward Gerstenfeld, Michael Lloyd, Petr Neuzil, Pugazhendhi Vijayaraman, Kenneth Ellenbogen, Margaret Infeld, Jeffrey Winterfield",
      "Affiliation": "Jiangsu Province Hospital; University of California, San Francisco; Emory University; Na Homolce Hospital; Geisinger Heart & Vascular Institute; Virginia Commonwealth University | Heart Rhythm Society; Tufts Medical Center; Medical University of South Carolina",
      "SpeakerTitles": "Professor of Medicine; Professor of Medicine; Director of EP Laboratories | Professor of Medicine | Cardiac Electrophysiologist; Head of the Department of Cardiology; Director, CCEP Fellowship; Director of Clinical Cardiac Electrophysiology and Pacing | Kimmerling Chair of Cardiology | President; Cardiac Electrophysiologist | Assistant Professor; Hank and Laurel Greer Chair in Clinical Cardiac Electrophysiology | Professor of Medicine",
      "session_id": 77,
      "uid": "s_77",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "09:35AM – 10:35AM",
      "room": "Main Stage 2",
      "type": "session",
      "Track": "Late-Breaking Clinical Trial",
      "Title": "Late-Breaking Clinical Trials: Innovations in Ablation & Electrophysiology Technologies",
      "Authors": "Dhanunjaya R. Lakkireddy, Devi G Nair, MD, FHRS, Douglas Packer, Vivek Y. Reddy, Ravi Ranjan, Andrea Sarkozy, Harikrishna Tandri",
      "Affiliation": "HCA Midwest in Overland Park, Kansas; St. Bernards Medical Center & Arrhythmia Research Group; Intermountain Medical Center; Mount Sinai Health System; University of Utah; Ventricular Arrhythmia & Sudden Death Unit, UZ Brussel; Vanderbilt University Medical Center",
      "SpeakerTitles": "Executive Medical Director of the Kansas City Heart Rhythm Institute; Director of the Cardiac Electrophysiology & Research; Professor of Medicine; Director of Cardiac Arrhythmia Services; Section Chief of Cardiac Electrophysiology; Professor of Cardiology & Free University of Brussels Director; Professor of Medicine; Chief of Electrophsyiology",
      "session_id": 78,
      "uid": "s_78",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "09:40AM – 10:00AM",
      "room": "Hyde Park",
      "type": "session",
      "Track": "Hot Takes Exchange",
      "Title": "We Can Cure Atrial Fibrillation",
      "Authors": "Mélèze Hocini, Dominik K Linz, MD, PhD, Kamala Tamirisa",
      "Affiliation": "Bordeaux University Hospital’s Cardiac Arrhythmias Center | IHU Liryc; Maastricht University Medical Center; UT Southwestern Medical Center",
      "SpeakerTitles": "Professor of Cardiology | Deputy Director; Professor | EP Consultant; Clinical Cardiac Electrophysiologist | Associate Professor of Internal Medicine in the Division of Cardiology | Director of Electrophysiology Research",
      "session_id": 79,
      "uid": "s_79",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "10:40AM – 11:25AM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "Session",
      "Title": "The Next PFA Frontier – Ventricular Ablation",
      "Authors": "Steven Mickelsen, Vivek Y. Reddy, Usha Tedrow, Edward Gerstenfeld",
      "Affiliation": "Field Medical | Atraverse Medical, Inc. | Scripps Health; Mount Sinai Health System; Brigham and Women’s Hospital | Harvard Medical School; University of California, San Francisco",
      "SpeakerTitles": "CEO | Board Member | Cardiac Electrophysiologist; Director of Cardiac Arrhythmia Services; Director, Clinical Cardiac Electrophysiology Program | Associate Professor of Medicine; Professor of Medicine",
      "session_id": 80,
      "uid": "s_80",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "10:40AM – 11:25AM",
      "room": "Roundtable 3",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Regulating AI Tools – A New Frontier",
      "Authors": "Mehak Dhande, Tony Fiola, Jackson Hair, Théophile Mohr Durdez, Chanda Owens, Yekaterina Spivak, Rachel Yung, Zak Loring",
      "Affiliation": "Stanford University, Stanford Healthcare; Global Cardiac Diagnostic Services Franchise at Boston Scientific; U.S. Food and Drug Administration; Volta Medical; iRhythm Technologies, Inc.; Children’s Hospital of Philadelphia | Welcome Baby 247; Duke University Medical Center",
      "SpeakerTitles": "Interventional Cardiac Electrophysiologist | Physician Scientist; Vice President & General Manager; Biomedical Engineer; CEO; Senior Vice President Quality & Regulatory; Pediatric Electrophysiology Physician Assistant | IBCLC & Co-founder; General Engineer; Cardiac Electrophysiologist",
      "session_id": 81,
      "uid": "s_81",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "10:40AM – 11:25AM",
      "room": "Main Stage 2",
      "type": "session",
      "Track": "Session",
      "Title": "Innovation & Development of New Tools for Lead Extraction",
      "Authors": "Ulrika Birgersdotter-Green, Mark Breyen, Pamela Mason, George Stuart Mendenhall, Oliver Monfredi, Jonathan Piccini",
      "Affiliation": "UC San Diego Health System; Philips; University of Virginia Health System; Scripps Memorial Hospital | Everbeat; University of Virginia; Duke University Hospital and the Duke Clinical Research Institute | Duke Heart Center",
      "SpeakerTitles": "Cardiac Electrophysiologist | Professor of Medicine; Vice President of Research and Development; Professor of Medicine; Cardiac Electrophysiologist and Researcher | Chief Medical Officer; Associate Professor of Medicine, Medical Director of the Complex Lead Management and Extraction Center of Excellence; Cardiac Electrophysiologist & Professor of Medicine and Population Health | Director of the Cardiac Electrophysiology section",
      "session_id": 82,
      "uid": "s_82",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "10:40AM – 11:25AM",
      "room": "Roundtable 1",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Cardioneuroablation: Which Patients, Which Endpoints, What Evidence?",
      "Authors": "Tolga Aksu, Piotr Kulakowski, Varun Malik, Stavros Stavrakis, Henry Huang",
      "Affiliation": "Istinye University Medical Park Florya Hospital, Department of Cardiology; Medical Center for Postgraduate Education, Grochowski Hospital; Adelaide University; University of Chicago | Journal of Interventional Cardiac Electrophysiology",
      "SpeakerTitles": "Professor of Cardiology and Cardiac Electrophysiology; Professor of Cardiology | Head of Electrophysiology Laboratory; Cardiac Electrophysiologist; Clinical Electrophysiologist | Associate Professor; Professor of Medicine, Director of Cardiac Electrophysiology | Editor-in-Chief",
      "session_id": 83,
      "uid": "s_83",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "10:40AM – 11:25AM",
      "room": "Roundtable 2",
      "type": "session",
      "Track": "Roundtable",
      "Title": "Getting New EP Devices Approved: Evidence, Regulation, and Reimbursement",
      "Authors": "Stephen Browning, Kevin Corriveau, Nassir Marrouche, Maria Stewart, J. Peter Weiss, Paul Wang",
      "Affiliation": "US Food & Drug Administration; Johnson & Johnson Medical Devices; Tulane University School of Medicine; Boston Scientific; Banner University of Arizona Medical Center Phoenix (BUMCP); Stanford Medicine",
      "SpeakerTitles": "Assistant Division Director; Director, U.S. Health Economics & Market Access; Director of Heart and Vascular Institute; Vice President, Health Economics & Market Access, AF Solutions and CRM-Dx; Cardiac Electrophysiologist; Director of the Stanford Cardiac Arrhythmia Service & Professor of Medicine and of Bioengineering",
      "session_id": 84,
      "uid": "s_84",
      "isMedtronic": false
    },
    {
      "day": "Sunday 9/20",
      "time": "11:25AM – 11:30AM",
      "room": "Main Stage 1",
      "type": "session",
      "Track": "General",
      "Title": "Closing Remarks from HRX Live 2026",
      "Authors": "Devi G Nair, MD, FHRS, Jonathan Piccini, Prashanthan Sanders",
      "Affiliation": "St. Bernards Medical Center & Arrhythmia Research Group; Duke University Hospital and the Duke Clinical Research Institute | Duke Heart Center; University of Adelaide",
      "SpeakerTitles": "Director of the Cardiac Electrophysiology & Research; Cardiac Electrophysiologist & Professor of Medicine and Population Health | Director of the Cardiac Electrophysiology section; Cardiac Electrophysiologist & Director of Cardiac Electrophysiology",
      "session_id": 85,
      "uid": "s_85",
      "isMedtronic": false
    }
  ]
}